name: Deploy Notebook to Kaggle
run-name: ${{ github.actor }} is deploying a notebook to Kaggle

on: 
    push:
        paths: ['session-resources/python-study-club/*.ipynb']

env:
    if: github.actor == 'sotirios-slv'
    KAGGLE_USERNAME: ${{ secrets.SOTIRIOS_KAGGLE_USERNAME }}

jobs:
    set-kaggle-credentials:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Job triggered by $KAGGLE_USERNAME"
